spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: userservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_4FF3SBfc6
server:
   port: 8083